baseURL = "https://angelo-blog.github.io/"
languageCode = "en-us"
title = "The Chopped Computer Scientist"
theme = "PaperMod"

[params]
  math = true
  ShowToc = true
  TocOpen = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

  
[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    noClasses = false
    lineNos = true
    style = "github"

[menu]
  [[menu.main]]
    name = "Math"
    url = "/math/"
    weight = 1

  [[menu.main]]
    name = "CP"
    url = "/cp/"
    weight = 2

  [[menu.main]]
    name = "Olympiad"
    url = "/olympiad/"
    weight = 3

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 5

  [[menu.main]]
    name = "Low Level"
    url = "/low-level-programming/"
    weight = 6
